Repository findologic/plugin-plentymarkets-ceres-api, pull requests merged in 2019-07, with the labels that each got.

#74 PLENTY-126 Upate user guides
  meta/documents/user_guide_de.md
  meta/documents/user_guide_en.md
Labels: enhancement, next release

#70 PLENTY-95 Add support for more sorting options
  src/Api/Request/ParametersBuilder.php
  src/Constants/Plugin.php
  tests/Api/Request/ParametersBuilderTest.php
  tests/Api/Request/RequestBuilderTest.php
  tests/Api/Request/RequestTest.php
  tests/Api/Response/Parser/FiltersParserTest.php
  tests/Api/Response/ResponseParserTest.php
  tests/Services/Search/ParametersHandlerTest.php
Labels: bug, next release

#76 PLENTY-127 Integrate new findologic snippet
  config.json
  resources/lang/de/Config.properties
  resources/lang/en/Config.properties
  resources/views/content/scripts.twig
  src/Constants/Plugin.php
  src/Middlewares/Middleware.php
Labels: enhancement, next release

#77 PLENTY-110 Get current plugin version from system
  src/Api/Request/RequestBuilder.php
  src/Constants/Plugin.php
Labels: enhancement, next release

#78 PLENTY-131_update_descr_and_screenshots
  meta/documents/user_guide_de.md
  meta/documents/user_guide_en.md
  meta/images/shopkey_config_de.png
  meta/images/shopkey_config_en.png
Labels: enhancement, next release

#82 PLENTY-128 Get third party js libraries from cdn
  resources/views/content/scripts.twig
  resources/views/content/styles.twig
Labels: enhancement, next release

#84 PLENTY-137 Update plugin version constraints
  plugin.json
Labels: enhancement, next release

#88 PLENTY-135 Update lodash dependency
  gulpfile.js
  package-lock.json
  package.json
Labels: enhancement, next release

#87 PLENTY-134 Support promotions
  plugin.json
  resources/css/findologic.css
  resources/views/Category/Item/Partials/Promotion.twig
  src/Api/Response/ResponseParser.php
  src/Containers/PromotionContainer.php
  tests/Api/Response/ResponseParserTest.php
Labels: enhancement, next release

#86 PLENTY-133 Support landing pages
  src/Api/Response/ResponseParser.php
  tests/Api/Response/ResponseParserTest.php
Labels: enhancement, next release

#90 PLENTY-141 version from constant
  plugin.json
  src/Api/Request/RequestBuilder.php
  src/Constants/Plugin.php
Labels: bug
