Repository findologic/plugin-plentymarkets-ceres-api, pull requests merged in 2019-09, with the labels that each got.

#104 PLENTY-145 Get selected filters from API response
  resources/js/dist/filters-component-min.js
  resources/js/dist/filters-component-min.js.map
  resources/js/dist/filters-component.js
  resources/js/dist/filters-component.js.map
  resources/js/src/app/components/itemList/filter/ItemFilter.js
  resources/views/ItemList/Components/Filter/ItemColorTiles.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  src/Api/Response/Parser/FiltersParser.php
  tests/Api/Response/Parser/FiltersParserTest.php
Labels: enhancement

#103 PLENTY-146 Convert existing styles to SCSS
  resources/css/findologic.css
  resources/css/findologic.min.css
  resources/scss/findologic.scss
  resources/scss/views/Category/Item/Partials/promotion.scss
  resources/scss/views/ItemList/Components/Filter/item-filter-list.scss
  resources/scss/views/ItemList/Components/item-color-tiles.scss
  resources/scss/views/ItemList/Components/item-range-slider.scss
  resources/scss/views/ItemList/Components/item-search.scss
Labels: enhancement, future release

#81 Plenty 129 add support for filter type dropdown
  gulpfile.js
  resources/css/findologic.css
  resources/js/dist/filters-component-min.js
  resources/js/dist/filters-component-min.js.map
  resources/js/dist/filters-component.js
  resources/js/dist/filters-component.js.map
  resources/js/src/app/components/itemList/filter/ItemDropdown.js
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/views/ItemList/Components/Filter/FiltersContainer.twig
  resources/views/ItemList/Components/Filter/ItemDropdown.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  resources/views/ItemList/Components/Filter/ItemRangeSlider.twig
Labels: enhancement, future release

#105 PLENTY-152 only single value allowed
  resources/js/dist/filters-component-min.js
  resources/js/dist/filters-component-min.js.map
  resources/js/dist/filters-component.js
  resources/js/dist/filters-component.js.map
  resources/js/src/app/mixins/url.js
Labels: bug, next release

#95 PLENTY-142 Support XML 2.1
  README.md
  composer.json
  composer.lock
  gulpfile.js
  package-lock.json
  package.json
  resources/css/findologic.css
  resources/css/findologic.min.css
  resources/css/findologic.min.css.map
  resources/js/dist/filters-component-min.js
  resources/js/dist/filters-component-min.js.map
  resources/js/dist/filters-component.js
  resources/js/dist/filters-component.js.map
  resources/js/src/app/components/itemList/filter/ItemDropdown.js
  resources/js/src/app/components/itemList/filter/ItemFilter.js
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/scss/findologic.scss
  resources/scss/views/Category/Item/Partials/promotion.scss
  resources/scss/views/ItemList/Components/Filter/item-color-tiles.scss
  resources/scss/views/ItemList/Components/Filter/item-dropdown.scss
  resources/scss/views/ItemList/Components/Filter/item-filter-list.scss
  resources/scss/views/ItemList/Components/Filter/item-range-slider.scss
  resources/scss/views/ItemList/Components/item-search.scss
  resources/views/Category/Item/Partials/SearchFilters.twig
  resources/views/ItemList/Components/Filter/FiltersContainer.twig
  resources/views/ItemList/Components/Filter/ItemColorTiles.twig
  resources/views/ItemList/Components/Filter/ItemDropdown.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  resources/views/ItemList/Components/Filter/ItemFilterList.twig
  resources/views/content/styles.twig
  src/Api/Request/RequestBuilder.php
  src/Api/Response/Parser/FiltersParser.php
  src/Api/Response/ResponseParser.php
  src/Constants/Plugin.php
  src/Containers/SearchFilterContainer.php
  tests/Api/Request/RequestBuilderTest.php
  tests/Api/Response/Parser/FiltersParserTest.php
  tests/Api/Response/ResponseParserTest.php
Labels: enhancement, next release

#113 PLENTY-151 Remove installation guide and add links to documentation
  meta/documents/support_contact_de.md
  meta/documents/support_contact_en.md
  meta/documents/user_guide_de.md
  meta/documents/user_guide_en.md
  meta/images/shopkey_config_de.png
  meta/images/shopkey_config_en.png
Labels: enhancement, next release

#115 PLENTY-154 Whole category tree is marked as selected
  src/Api/Response/Parser/FiltersParser.php
  tests/Api/Response/Parser/FiltersParserTest.php
Labels: bug, next release

#108 PLENTY-124 Errors in console in development mode
  resources/views/Category/Item/Partials/ItemSearch.twig
  resources/views/ItemList/Components/ItemSearch.twig
  src/Containers/SearchBarContainer.php
Labels: bug, next release

#117 PLENTY-149 Consider fixed filter values for dropdowns
  meta/documents/support_contact_de.md
  meta/documents/support_contact_en.md
  meta/documents/user_guide_de.md
  meta/documents/user_guide_en.md
  meta/images/shopkey_config_de.png
  meta/images/shopkey_config_en.png
  resources/css/findologic.min.css
  resources/css/findologic.min.css.map
  resources/scss/findologic.scss
  resources/scss/views/ItemList/Components/Filter/item-dropdown.scss
  resources/scss/views/ItemList/Components/Filter/item-filter.scss
  resources/views/Category/Item/Partials/ItemSearch.twig
  resources/views/ItemList/Components/Filter/ItemDropdown.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  resources/views/ItemList/Components/ItemSearch.twig
  src/Api/Response/Parser/FiltersParser.php
  src/Containers/SearchBarContainer.php
  tests/Api/Response/Parser/FiltersParserTest.php
Labels: enhancement, next release

#119 Darius adeoweb plenty 149 consider fixed filter values for dropdowns
  resources/css/findologic.min.css
  resources/css/findologic.min.css.map
  resources/scss/views/ItemList/Components/Filter/item-dropdown.scss
  resources/views/ItemList/Components/Filter/ItemDropdown.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  src/Api/Response/Parser/FiltersParser.php
  tests/Api/Response/Parser/FiltersParserTest.php
Labels: enhancement, next release
