Repository findologic/plugin-plentymarkets-ceres-api, pull requests merged in 2020-03, with the labels that each got.

#159 PLENTY-207 Fix search results
  resources/css/findologic.min.css
  resources/css/findologic.min.css.map
  resources/js/dist/filters-component-min.js
  resources/js/dist/filters-component-min.js.map
  resources/js/dist/filters-component.js
  resources/js/dist/filters-component.js.map
  resources/js/src/app/components/itemList/filter/ItemFilter.js
  resources/scss/views/ItemList/Components/Filter/item-filter-list.scss
  resources/views/Category/Item/Partials/SearchFilters.twig
  resources/views/ItemList/Components/Filter/ItemColorTiles.twig
  resources/views/ItemList/Components/Filter/ItemDropdown.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  resources/views/ItemList/Components/Filter/ItemFilterList.twig
  resources/views/ItemList/Components/Filter/ItemFilterTagList.twig
  resources/views/ItemList/Components/Filter/ItemRangeSlider.twig
  src/Services/SearchService.php
  tests/Services/SearchServiceTest.php
Labels: beta5, enhancement

#160 PLENTY-208 Fix navigation
  src/Services/FallbackSearchService.php
Labels: beta5, enhancement

#163 PLENTY-211 Product sorting
  src/Services/SearchService.php
  tests/Services/SearchServiceTest.php
Labels: beta5, bug

#164 PLENTY-210 Fix error if all filters are configured as "other filter"
  resources/views/ItemList/Components/Filter/ItemFilterList.twig
Labels: bug, next release

#158 PLENTY-209 Fix product redirect url
  src/Services/SearchService.php
  tests/Services/SearchServiceTest.php
Labels: bug, next release

#155 PLENTY-200 On navigation show plentymarkets sorting
  src/Services/Search/ParametersHandler.php
  tests/Services/Search/ParametersHandlerTest.php
  tests/Services/SearchServiceTest.php
Labels: bug, next release

#153 PLENTY-204_update_english_docu_link
  meta/documents/support_contact_en.md
Labels: enhancement, next release

#154 PLENTY-199_dropdown_filters_should_have_a_max_height
  resources/css/findologic.min.css
  resources/css/findologic.min.css.map
  resources/scss/views/ItemList/Components/Filter/item-dropdown.scss
Labels: enhancement, next release

#157 PLENTY-192 Filter by cat id
  src/Api/Request/ParametersBuilder.php
  src/Api/Request/RequestBuilder.php
  src/Helpers/Tags.php
  tests/Api/Request/ParametersBuilderTest.php
  tests/Api/Request/RequestBuilderTest.php
Labels: enhancement, next release

#167 PLENTY-216 Add version contstraint
  meta/documents/user_guide_de.md
  meta/documents/user_guide_en.md
  plugin.json
Labels: enhancement, next release

#177 PLENTY-217_update_user_guide_5_0
  meta/documents/user_guide_de.md
  meta/documents/user_guide_en.md
Labels: beta5, enhancement
