Repository findologic/plugin-plentymarkets-ceres-api, pull requests merged in 2020-04, with the labels that each got.

#174 PLENTY-220_fix_shopbuilder_filter_button
  composer.json
  composer.lock
  resources/css/findologic.min.css
  resources/css/findologic.min.css.map
  resources/scss/findologic.scss
  resources/scss/shop-builder.scss
  resources/scss/views/ItemList/Components/Filter/item-filter.scss
Labels: bug, next release

#178 PLENTY-229_adapt_translation_queryInfo_SDYM
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/views/Category/Item/Partials/SmartDidYouMean.twig
  src/Api/Response/Response.php
  src/Containers/SmartDidYouMeanContainer.php
  tests/Api/Response/ResponseTest.php
Labels: enhancement, next release

#181 PLENTY-231 Dont show broken images for color tiles
  resources/views/ItemList/Components/Filter/ItemColorTiles.twig
Labels: enhancement, next release

#182 PLENTY-196 nofollow attribute for filters
  resources/views/ItemList/Components/Filter/ItemColorTiles.twig
  resources/views/ItemList/Components/Filter/ItemDropdown.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  resources/views/ItemList/Components/Filter/ItemRangeSlider.twig
Labels: enhancement, next release

#183 PLENTY-193 Make filter rows configurable
  config.json
  resources/lang/de/Config.properties
  resources/lang/en/Config.properties
  resources/views/ItemList/Components/Filter/ItemFilter.twig
Labels: enhancement, next release

#179 Plenty 196 nofollow attribute on filter items
  resources/views/ItemList/Components/Filter/ItemColorTiles.twig
  resources/views/ItemList/Components/Filter/ItemDropdown.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  resources/views/ItemList/Components/Filter/ItemFilterPrice.twig
  resources/views/ItemList/Components/Filter/ItemFilterTagList.twig
  resources/views/ItemList/Components/Filter/ItemRangeSlider.twig
Labels: beta5, enhancement

#186 PLENTY-227 submit data from the correct search field when there are m…
  resources/views/ItemList/Components/ItemSearch.twig
  resources/views/content/scripts.twig
Labels: beta5, bug

#187 PLENTY-234_update_marketplace_images_and_text
  meta/documents/user_guide_de.md
  meta/documents/user_guide_en.md
  meta/images/icon_author_md.png
  meta/images/icon_author_md_2.png
  meta/images/icon_author_sm.png
  meta/images/icon_author_sm_2.png
  meta/images/icon_author_xs.png
  meta/images/icon_author_xs_2.png
  meta/images/icon_plugin_md.png
  meta/images/icon_plugin_sm.png
  meta/images/icon_plugin_xs.png
  meta/images/preview_0.png
  meta/images/preview_1.png
  meta/images/preview_2.png
  meta/images/preview_3.png
  meta/images/preview_4.png
  meta/images/preview_5.png
Labels: beta5, enhancement

#165 PLENTY-205 Prepare for Ceres 5.0.0
  .travis.yml
  composer.json
  composer.lock
  meta/documents/changelog_de.md
  meta/documents/changelog_en.md
  meta/documents/user_guide_de.md
  meta/documents/user_guide_en.md
  meta/images/icon_author_md.png
  meta/images/icon_author_md_2.png
  meta/images/icon_author_sm.png
  meta/images/icon_author_sm_2.png
  meta/images/icon_author_xs.png
  meta/images/icon_author_xs_2.png
  meta/images/icon_plugin_md.png
  meta/images/icon_plugin_sm.png
  meta/images/icon_plugin_xs.png
  meta/images/preview_0.png
  meta/images/preview_1.png
  meta/images/preview_2.png
  meta/images/preview_3.png
  meta/images/preview_4.png
  meta/images/preview_5.png
  package-lock.json
  plugin.json
  resources/css/findologic.min.css
  resources/css/findologic.min.css.map
  resources/js/dist/filters-component-min.js
  resources/js/dist/filters-component-min.js.map
  resources/js/dist/filters-component.js
  resources/js/dist/filters-component.js.map
  resources/js/src/app/components/itemList/filter/ItemFilter.js
  resources/scss/views/ItemList/Components/Filter/item-dropdown.scss
  resources/scss/views/ItemList/Components/Filter/item-filter-list.scss
  resources/views/Category/Item/Partials/SearchFilters.twig
  resources/views/ItemList/Components/Filter/ItemColorTiles.twig
  resources/views/ItemList/Components/Filter/ItemDropdown.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  resources/views/ItemList/Components/Filter/ItemFilterList.twig
  resources/views/ItemList/Components/Filter/ItemFilterPrice.twig
  resources/views/ItemList/Components/Filter/ItemFilterTagList.twig
  resources/views/ItemList/Components/Filter/ItemRangeSlider.twig
  resources/views/ItemList/Components/ItemSearch.twig
  resources/views/content/scripts.twig
  src/Constants/Plugin.php
  src/Services/FallbackSearchService.php
  src/Services/SearchService.php
  tests/Mocks/PlentyRequestMock.php
  tests/Services/SearchServiceTest.php
Labels: beta5, enhancement, next release

#189 PLENTY-232_change_default_no_color_filter_image
  resources/images/no-picture.jpg
  resources/images/no-picture.png
  resources/views/ItemList/Components/Filter/ItemColorTiles.twig
Labels: enhancement, next release

#188 PLENTY-239_update_marketplace_image
  meta/images/icon_author_xs.png
  meta/images/icon_plugin_xs.png
Labels: enhancement, next release
